easy_admin:
    site_name: 'Dropshipping Admin Panel'
    
    # Global design configuration
    design:
        brand:
            color: '#1976d2'
        
    # Global formats
    formats:
        date: 'd/m/Y'
        time: 'H:i'
        datetime: 'd/m/Y H:i:s'
        
    # Global assets
    assets:
        css:
            - 'assets/styles/admin.css'