# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session:
        # Session timeout after 30 minutes of inactivity
        gc_maxlifetime: 1800
        cookie_lifetime: 1800
        cookie_secure: auto
        cookie_httponly: true

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
